version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_gerencia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gerencia_restaurante
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gerencia-network

  app:
    build: .
    container_name: gerencia_restaurante_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_gerencia:3306/gerencia_restaurante?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - gerencia-network

volumes:
  mysql_data:

networks:
  gerencia-network:
    driver: bridge
