spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gerencia_restaurante?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

resilience4j:
  retry:
    instances:
      ifoodConfirm:
        max-attempts: 5           # tenta 5 vezes
        wait-duration: 3s         # espera 3 segundos entre tentativas
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException

ifood:
  client-id: ea2ea14e-94e9-48a1-8a5d-cab6705e482d
  client-secret: 3b152j671uh8xid4po88q54b8c4afnuc60rw7o9dnd513x91tr6w6z163wnm7ggmdlywzliqu8lbt3wx0frl17mhcwjnqoem49r
  auth-url: https://merchant-api.ifood.com.br/authentication/v1.0/oauth/token
  base-url: https://merchant-api.ifood.com.br